// Banco adicional de questões — usado para evitar repetição entre lições.
import type { Exercise } from "./questions";

const sel = (prompt: string, options: string[], answer: number): Exercise => ({
  kind: "select",
  prompt,
  options,
  answer,
});
const tf = (prompt: string, answer: boolean): Exercise => ({ kind: "truefalse", prompt, answer });
const asm = (prompt: string, sentence: string): Exercise => ({ kind: "assemble", prompt, sentence });
const typ = (prompt: string, answer: string): Exercise => ({ kind: "type", prompt, answer });

type ExtraBank = { f1?: Exercise[]; f2?: Exercise[]; f3?: Exercise[]; em?: Exercise[]; all?: Exercise[] };

export const EXTRA_BANKS: Record<string, ExtraBank> = {
  portugues: {
    f1: [
      sel("Qual palavra tem 3 sílabas?", ["Ba-na-na", "Bo-la", "Pé", "Sol"], 0),
      sel("Qual letra é consoante?", ["P", "A", "E", "O"], 0),
      sel("Qual palavra começa com a mesma letra de PATO?", ["Pente", "Gato", "Bola", "Lua"], 0),
      typ("Escreva o nome do animal que mia.", "gato"),
      tf("A palavra SOL tem três letras.", true),
      asm("Monte a frase", "a menina brinca na praça"),
      sel("Qual é o plural de 'flor'?", ["Flores", "Florais", "Floros", "Flor"], 0),
      sel("Qual palavra rima com MÃO?", ["Pão", "Mesa", "Livro", "Céu"], 0),
      tf("Usamos ponto de interrogação quando fazemos uma pergunta.", true),
      asm("Monte a frase", "meu pai lê um livro"),
      sel("Quantas vogais tem a palavra ABELHA?", ["3", "2", "4", "5"], 0),
      typ("Complete: o contrário de dia é ____.", "noite"),
    ],
    f2: [
      sel("Qual palavra é um verbo?", ["Pular", "Bonita", "Mesa", "Rápido"], 0),
      sel("Qual é o feminino de 'ator'?", ["Atriz", "Atora", "Atriza", "Atore"], 0),
      sel("Qual é o aumentativo de 'casa'?", ["Casarão", "Casinha", "Casebre", "Casal"], 0),
      sel("Qual é o diminutivo de 'livro'?", ["Livrinho", "Livrão", "Livraria", "Livreiro"], 0),
      sel("Em 'A Ana correu', quem praticou a ação?", ["Ana", "correu", "A", "ninguém"], 0),
      sel("Qual palavra tem acento agudo?", ["Café", "Casa", "Bola", "Mesa"], 0),
      asm("Monte a frase", "nós fomos ao parque no domingo"),
      typ("Escreva o antônimo de 'quente'.", "frio"),
      tf("Verbos indicam ação, estado ou fenômeno.", true),
      sel("Qual frase está no passado?", ["Ele estudou ontem.", "Ele estuda hoje.", "Ele estudará amanhã.", "Ele está estudando."], 0),
      sel("Qual palavra é escrita com SS?", ["Pássaro", "Pásaro", "Paçaro", "Pazaro"], 0),
      sel("A vírgula serve para:", ["Marcar pausa na frase", "Terminar o texto", "Fazer pergunta", "Gritar"], 0),
    ],
    f3: [
      sel("Em 'Ele viajou rapidamente', a palavra destacada é:", ["Advérbio", "Adjetivo", "Substantivo", "Verbo"], 0),
      sel("Qual é um pronome possessivo?", ["Meu", "Ele", "Aquele", "Quem"], 0),
      sel("Em 'Comprei livros e cadernos', a conjunção 'e' indica:", ["Adição", "Oposição", "Conclusão", "Alternância"], 0),
      sel("Oração sem sujeito aparece em:", ["Choveu ontem.", "Maria saiu.", "Nós fomos.", "Eles chegaram."], 0),
      sel("Em 'Preciso de ajuda', o termo 'de ajuda' é:", ["Complemento nominal", "Sujeito", "Aposto", "Vocativo"], 0),
      sel("Qual palavra é proparoxítona?", ["Médico", "Cadeira", "Café", "Papel"], 0),
      sel("Qual figura aparece em 'O silêncio gritou'?", ["Paradoxo", "Metonímia", "Eufemismo", "Pleonasmo"], 0),
      asm("Monte o período", "embora estivesse cansado ele terminou o trabalho"),
      tf("Predicado verbal tem como núcleo um verbo significativo.", true),
      sel("A crase ocorre pela fusão de:", ["Preposição a + artigo a", "Dois verbos", "Dois substantivos", "Artigo + adjetivo"], 0),
      typ("Qual é o plural de 'cidadão'? (uma palavra)", "cidadaos"),
      sel("Em 'A casa cujo telhado caiu', 'cujo' é pronome:", ["Relativo", "Pessoal", "Indefinido", "Demonstrativo"], 0),
    ],
    em: [
      sel("Na função metalinguística, a linguagem fala sobre:", ["A própria linguagem", "O emissor", "O receptor", "O canal"], 0),
      sel("'Ele partiu desta para melhor' é exemplo de:", ["Eufemismo", "Hipérbole", "Ironia", "Metonímia"], 0),
      sel("Intertextualidade é:", ["Diálogo entre textos", "Erro de escrita", "Tipo de acento", "Sinônimo de coesão"], 0),
      sel("Na redação do ENEM, a competência 1 avalia:", ["Domínio da norma culta", "Proposta de intervenção", "Coesão", "Tese"], 0),
      sel("Em 'Não gosto de futebol, mas assisti ao jogo', a relação é de:", ["Adversidade", "Causa", "Finalidade", "Condição"], 0),
      sel("Qual é a função da linguagem predominante em propagandas?", ["Conativa", "Poética", "Referencial", "Fática"], 0),
      sel("Denotação é o uso da palavra em sentido:", ["Literal", "Figurado", "Irônico", "Poético"], 0),
      sel("Em 'Li Machado de Assis', temos:", ["Metonímia (autor pela obra)", "Metáfora", "Hipérbato", "Catacrese"], 0),
      asm("Monte a tese", "o acesso à informação é essencial para a cidadania"),
      tf("Argumento de autoridade cita especialistas ou fontes reconhecidas.", true),
      sel("Coerência textual diz respeito a:", ["Sentido lógico do texto", "Uso de vírgulas", "Tamanho do texto", "Letra bonita"], 0),
      sel("Norma-padrão é:", ["Variedade prestigiada e registrada em gramáticas", "Gíria juvenil", "Fala regional", "Erro de português"], 0),
    ],
  },

  ciencias: {
    f1: [
      sel("Qual sentido usamos para ouvir?", ["Audição", "Visão", "Tato", "Paladar"], 0),
      sel("O que os animais precisam para viver?", ["Água e alimento", "Só brinquedos", "Só sol", "Nada"], 0),
      tf("A borboleta nasce de uma lagarta.", true),
      sel("Qual parte da planta fica embaixo da terra?", ["Raiz", "Folha", "Flor", "Fruto"], 0),
      sel("Quando é noite, vemos no céu:", ["A Lua e estrelas", "O Sol forte", "Arco-íris", "Nuvens coloridas"], 0),
      sel("Para ficar saudável devemos:", ["Comer frutas e verduras", "Só doces", "Nunca dormir", "Ficar parado"], 0),
      tf("O passarinho é um animal que voa.", true),
      sel("O que usamos para escovar os dentes?", ["Escova e pasta", "Sabão em pó", "Água suja", "Areia"], 0),
      sel("A chuva vem de onde?", ["Das nuvens", "Do chão", "Das árvores", "Do fogo"], 0),
      tf("As plantas precisam de água para crescer.", true),
    ],
    f2: [
      sel("Qual é o gás que respiramos para viver?", ["Oxigênio", "Gás carbônico", "Nitrogênio puro", "Hélio"], 0),
      sel("A evaporação transforma a água em:", ["Vapor", "Gelo", "Pedra", "Areia"], 0),
      sel("Animais que mamam quando filhotes são:", ["Mamíferos", "Aves", "Répteis", "Peixes"], 0),
      sel("O que é um habitat?", ["Lugar onde um ser vivo vive", "Um alimento", "Uma doença", "Uma estação"], 0),
      tf("A Lua é um satélite natural da Terra.", true),
      sel("Cadeia alimentar começa geralmente com:", ["Produtores (plantas)", "Carnívoros", "Decompositores", "Ar"], 0),
      sel("O solo fértil é importante para:", ["O cultivo de plantas", "Fazer vidro", "Produzir energia solar", "Nada"], 0),
      sel("Qual atitude preserva o meio ambiente?", ["Economizar água", "Jogar lixo na rua", "Desmatar", "Poluir rios"], 0),
      tf("As estações do ano acontecem por causa da inclinação e do movimento da Terra.", true),
      sel("Os pulmões fazem parte do sistema:", ["Respiratório", "Digestório", "Nervoso", "Ósseo"], 0),
    ],
    f3: [
      sel("Qual organela produz energia na célula?", ["Mitocôndria", "Núcleo", "Ribossomo", "Vacúolo"], 0),
      sel("A velocidade da luz no vácuo é aproximadamente:", ["300.000 km/s", "300 km/s", "3.000 km/h", "30 m/s"], 0),
      sel("O que é uma mistura homogênea?", ["Aquela com aspecto uniforme", "Aquela com fases visíveis", "Só sólidos", "Só gases"], 0),
      sel("A 3ª Lei de Newton trata de:", ["Ação e reação", "Inércia", "Aceleração", "Energia"], 0),
      sel("O sangue é bombeado pelo:", ["Coração", "Fígado", "Pâncreas", "Baço"], 0),
      tf("Ondas sonoras precisam de um meio material para se propagar.", true),
      sel("A tabela periódica agrupa elementos em:", ["Períodos e famílias", "Cores e formas", "Tamanhos", "Sabores"], 0),
      sel("O ciclo da água inclui:", ["Evaporação, condensação e precipitação", "Só chuva", "Só rios", "Só oceanos"], 0),
      sel("Fotossíntese consome:", ["Gás carbônico e água", "Só oxigênio", "Só glicose", "Nitrogênio"], 0),
      tf("A energia não é criada nem destruída, apenas transformada.", true),
    ],
  },

  historia: {
    f1: [
      sel("Quem faz parte da comunidade escolar?", ["Alunos, professores e funcionários", "Somente diretores", "Somente pais", "Ninguém"], 0),
      sel("Um objeto antigo da família é considerado:", ["Uma fonte histórica", "Um brinquedo novo", "Um mapa", "Uma receita"], 0),
      tf("Cada pessoa tem uma história de vida diferente.", true),
      sel("O que comemoramos no aniversário?", ["A passagem de mais um ano", "O fim do mês", "O feriado", "A chuva"], 0),
      sel("Regras servem para:", ["Organizar a convivência", "Atrapalhar", "Enfeitar", "Nada"], 0),
      tf("O relógio e o calendário ajudam a medir o tempo.", true),
      sel("Antigamente as pessoas se comunicavam por:", ["Cartas", "Aplicativos", "Redes sociais", "Videochamadas"], 0),
    ],
    f2: [
      sel("Quem comandou a esquadra que chegou ao Brasil em 1500?", ["Pedro Álvares Cabral", "Cristóvão Colombo", "Dom Pedro I", "Tiradentes"], 0),
      sel("A Inconfidência Mineira tinha como líder símbolo:", ["Tiradentes", "Dom João VI", "Zumbi", "Anchieta"], 0),
      sel("Quilombo dos Palmares foi liderado por:", ["Zumbi", "Cabral", "Getúlio", "Dom Pedro II"], 0),
      sel("O primeiro produto explorado no Brasil colônia foi:", ["Pau-brasil", "Café", "Soja", "Petróleo"], 0),
      tf("Dom Pedro I proclamou a Independência às margens do Ipiranga.", true),
      sel("Os bandeirantes ficaram conhecidos por:", ["Expedições ao interior", "Construir navios", "Criar escolas", "Fazer leis"], 0),
      sel("A Lei Áurea foi assinada por:", ["Princesa Isabel", "Dom Pedro I", "Getúlio Vargas", "Tiradentes"], 0),
      tf("O ciclo do ouro ocorreu principalmente em Minas Gerais.", true),
    ],
    f3: [
      sel("A Primeira Guerra Mundial começou em:", ["1914", "1939", "1789", "1822"], 0),
      sel("O nazismo foi liderado na Alemanha por:", ["Hitler", "Mussolini", "Stálin", "Churchill"], 0),
      sel("O Renascimento valorizava:", ["O ser humano e a razão", "O feudalismo", "A servidão", "O misticismo medieval"], 0),
      sel("As Grandes Navegações foram impulsionadas por:", ["Busca de novas rotas comerciais", "Turismo", "Esporte", "Curiosidade apenas"], 0),
      sel("A Revolução Industrial trouxe:", ["Máquinas e produção em fábricas", "Fim do comércio", "Volta ao feudalismo", "Redução das cidades"], 0),
      tf("O Muro de Berlim caiu em 1989.", true),
      sel("A Semana de Arte Moderna aconteceu no Brasil em:", ["1922", "1889", "1945", "1964"], 0),
      sel("A Guerra do Paraguai envolveu o Brasil no século:", ["XIX", "XVI", "XX", "XVIII"], 0),
    ],
    em: [
      sel("O mercantilismo se baseava em:", ["Metalismo e balança comercial favorável", "Livre mercado total", "Socialismo", "Feudalismo"], 0),
      sel("A Guerra Fria terminou com:", ["O fim da URSS em 1991", "A Primeira Guerra", "A Revolução Francesa", "O Tratado de Tordesilhas"], 0),
      sel("A Revolução Industrial inglesa foi favorecida por:", ["Carvão, capital e mão de obra", "Ausência de comércio", "Isolamento total", "Falta de tecnologia"], 0),
      sel("A Constituição de 1824 foi outorgada por:", ["Dom Pedro I", "Dom Pedro II", "Deodoro", "Vargas"], 0),
      sel("O golpe militar de 1964 derrubou o presidente:", ["João Goulart", "Juscelino", "Jânio Quadros", "Dutra"], 0),
      sel("A política do café com leite envolvia:", ["São Paulo e Minas Gerais", "Rio e Bahia", "Ceará e Pará", "Sul e Norte"], 0),
      tf("O apartheid foi um regime de segregação racial na África do Sul.", true),
      sel("A Descolonização da África se intensificou:", ["Após a Segunda Guerra Mundial", "No século XVI", "Na Idade Média", "Em 1822"], 0),
    ],
  },

  geografia: {
    f1: [
      sel("O que é uma rua?", ["Um caminho onde passam pessoas e carros", "Um rio", "Uma escola", "Uma montanha"], 0),
      sel("O Sol nasce no:", ["Leste", "Oeste", "Norte", "Sul"], 0),
      tf("No campo há mais plantações do que na cidade.", true),
      sel("Qual desses é um elemento da natureza?", ["Rio", "Prédio", "Carro", "Ponte"], 0),
      sel("Para atravessar a rua com segurança usamos:", ["A faixa de pedestres", "O meio da pista", "A calçada do vizinho", "Nada"], 0),
      tf("A escola faz parte do bairro onde moramos.", true),
      sel("Qual paisagem é natural?", ["Floresta", "Shopping", "Rodovia", "Praça construída"], 0),
    ],
    f2: [
      sel("Qual é o maior bioma brasileiro?", ["Amazônia", "Pampa", "Pantanal", "Caatinga"], 0),
      sel("A Caatinga é típica de qual região?", ["Nordeste", "Sul", "Norte", "Centro-Oeste"], 0),
      sel("Rio que corta grande parte do Nordeste:", ["São Francisco", "Amazonas", "Paraná", "Tietê"], 0),
      sel("Qual é o estado mais populoso do Brasil?", ["São Paulo", "Acre", "Sergipe", "Roraima"], 0),
      tf("A rosa dos ventos indica os pontos cardeais.", true),
      sel("O relevo é o conjunto de:", ["Formas da superfície terrestre", "Tipos de clima", "Rios", "Cidades"], 0),
      sel("A migração campo-cidade é chamada de:", ["Êxodo rural", "Imigração", "Turismo", "Nomadismo"], 0),
      tf("O Pantanal é a maior planície alagável do mundo.", true),
    ],
    f3: [
      sel("Fuso horário existe por causa do movimento de:", ["Rotação", "Translação", "Precessão", "Nutação"], 0),
      sel("Chuva ácida é causada por:", ["Poluentes como enxofre e nitrogênio", "Vapor puro", "Vento", "Neve"], 0),
      sel("Urbanização é o crescimento:", ["Das cidades", "Das florestas", "Dos oceanos", "Dos desertos"], 0),
      sel("Qual é o continente mais extenso?", ["Ásia", "África", "Europa", "Oceania"], 0),
      sel("Latitude mede a distância em relação à:", ["Linha do Equador", "Greenwich", "Trópico de Câncer", "Polo Norte"], 0),
      tf("A Amazônia sofre pressão do desmatamento pela pecuária e agricultura.", true),
      sel("Setor terciário da economia corresponde a:", ["Comércio e serviços", "Agricultura", "Indústria", "Mineração"], 0),
      sel("Ilha é uma porção de terra cercada de:", ["Água por todos os lados", "Terra", "Gelo apenas", "Areia"], 0),
    ],
    em: [
      sel("Meridiano de Greenwich serve de referência para:", ["Longitude", "Latitude", "Altitude", "Relevo"], 0),
      sel("Agronegócio brasileiro se destaca na exportação de:", ["Soja e carne", "Automóveis de luxo", "Chips", "Petróleo refinado"], 0),
      sel("Pirâmide etária com base estreita indica:", ["Envelhecimento populacional", "Alta natalidade", "Explosão demográfica", "População jovem"], 0),
      sel("A Amazônia Legal abrange:", ["Nove estados brasileiros", "Todo o Brasil", "Apenas o Pará", "Três países"], 0),
      sel("A migração forçada por conflitos gera:", ["Refugiados", "Turistas", "Nômades", "Comerciantes"], 0),
      tf("A União Europeia é um bloco econômico com moeda comum em vários países.", true),
      sel("Inversão térmica agrava:", ["A poluição do ar nas cidades", "As chuvas", "O relevo", "A maré"], 0),
      sel("Recursos renováveis incluem:", ["Energia solar e eólica", "Carvão mineral", "Petróleo", "Gás natural"], 0),
    ],
  },

  ingles: {
    f1: [
      sel("What is 'red'?", ["Vermelho", "Verde", "Azul", "Preto"], 0),
      sel("How do you say 'obrigado'?", ["Thank you", "Please", "Sorry", "Hello"], 0),
      sel("'Dog' means:", ["Cachorro", "Gato", "Pássaro", "Peixe"], 0),
      sel("'One, two, ___'", ["three", "four", "five", "ten"], 0),
      asm("Monte a frase em inglês", "I am six years old"),
      sel("'Good morning' é usado:", ["De manhã", "À noite", "À tarde", "Na madrugada"], 0),
      typ("Escreva em inglês a palavra 'casa'.", "house"),
      sel("'Mother' means:", ["Mãe", "Pai", "Irmã", "Avó"], 0),
    ],
    f2: [
      sel("Complete: She ___ to school every day.", ["goes", "go", "going", "gone"], 0),
      sel("What is 'apple'?", ["Maçã", "Uva", "Pera", "Banana"], 0),
      sel("Choose the question: ___ is your name?", ["What", "Who", "Where", "When"], 0),
      sel("'They are playing' está no:", ["Presente contínuo", "Passado simples", "Futuro", "Presente perfeito"], 0),
      asm("Monte a frase", "we like to study English"),
      sel("Plural of 'box':", ["boxes", "boxs", "boxen", "box"], 0),
      typ("Write the past of 'play'.", "played"),
      sel("'Where do you live?' pergunta sobre:", ["Lugar", "Tempo", "Motivo", "Pessoa"], 0),
    ],
    f3: [
      sel("Past of 'buy':", ["bought", "buyed", "boughted", "buying"], 0),
      sel("Superlative of 'big':", ["the biggest", "bigger", "most big", "biggest more"], 0),
      sel("'Can' expressa:", ["Habilidade ou permissão", "Obrigação total", "Passado", "Futuro certo"], 0),
      sel("Choose: 'I have lived here ___ 2015.'", ["since", "for", "during", "ago"], 0),
      asm("Monte a frase", "she has already finished her homework"),
      sel("'Must' indica:", ["Obrigação", "Possibilidade remota", "Passado", "Desejo"], 0),
      sel("Reported speech: He said he ___ tired.", ["was", "is", "will be", "be"], 0),
      typ("Write the opposite of 'expensive'.", "cheap"),
    ],
    em: [
      sel("'Nevertheless' means:", ["No entanto", "Portanto", "Porque", "Além disso"], 0),
      sel("Choose the phrasal verb meaning 'adiar':", ["put off", "put on", "put up", "put in"], 0),
      sel("'Pretend' is a false friend meaning:", ["Fingir", "Pretender", "Prevenir", "Preferir"], 0),
      sel("Third conditional: 'If I had studied, I ___ passed.'", ["would have", "will have", "would", "had"], 0),
      sel("Skimming a text means:", ["Reading quickly for the main idea", "Reading every word", "Translating", "Memorizing"], 0),
      asm("Build the sentence", "technology has changed the way we learn"),
      sel("'However' is used to:", ["Contrast ideas", "Add information", "Give a reason", "Conclude"], 0),
      tf("Cognatos são palavras parecidas em inglês e português com o mesmo sentido.", true),
    ],
  },

  fisica: {
    all: [
      sel("Aceleração da gravidade na Terra é aproximadamente:", ["9,8 m/s²", "1,8 m/s²", "98 m/s²", "0,98 m/s²"], 0),
      sel("Trabalho de uma força constante é:", ["W = F·d·cosθ", "W = m·a", "W = m·v", "W = F/d"], 0),
      sel("Unidade de energia no SI:", ["Joule", "Newton", "Watt", "Hertz"], 0),
      sel("No MRU a velocidade é:", ["Constante", "Crescente", "Nula", "Variável"], 0),
      sel("Empuxo é estudado pelo princípio de:", ["Arquimedes", "Pascal", "Bernoulli", "Newton"], 0),
      sel("A refração ocorre quando a luz:", ["Muda de meio e de velocidade", "Volta para o mesmo meio", "É absorvida", "Some"], 0),
      sel("Resistores em série têm resistência equivalente igual à:", ["Soma das resistências", "Média", "Inverso da soma", "Menor delas"], 0),
      sel("Potência elétrica é dada por:", ["P = U·i", "P = U/i", "P = i/U", "P = U + i"], 0),
      sel("Período e frequência se relacionam por:", ["T = 1/f", "T = f", "T = f²", "T = 2f"], 0),
      tf("Em uma queda livre ideal, todos os corpos caem com a mesma aceleração.", true),
      sel("A quantidade de movimento é dada por:", ["Q = m·v", "Q = m·a", "Q = F·t²", "Q = v/m"], 0),
      sel("A escala Kelvin começa no:", ["Zero absoluto", "Ponto de fusão do gelo", "Ponto de ebulição", "-100 °C"], 0),
    ],
  },
  quimica: {
    all: [
      sel("Isótopos possuem o mesmo número de:", ["Prótons", "Nêutrons", "Massa", "Elétrons livres"], 0),
      sel("A ligação entre dois ametais é:", ["Covalente", "Iônica", "Metálica", "Nenhuma"], 0),
      sel("Solução com pH 3 é:", ["Ácida", "Básica", "Neutra", "Salina"], 0),
      sel("H₂SO₄ é o:", ["Ácido sulfúrico", "Ácido clorídrico", "Hidróxido de sódio", "Óxido de cálcio"], 0),
      sel("Reação de neutralização produz:", ["Sal e água", "Só gás", "Só ácido", "Metal puro"], 0),
      sel("Catalisador em uma reação:", ["Aumenta a velocidade sem ser consumido", "É consumido", "Diminui sempre", "Muda o produto"], 0),
      sel("Massa molar da água (H₂O) é cerca de:", ["18 g/mol", "10 g/mol", "32 g/mol", "44 g/mol"], 0),
      sel("Na tabela periódica, a família 1 é dos:", ["Metais alcalinos", "Halogênios", "Gases nobres", "Calcogênios"], 0),
      tf("Reações endotérmicas absorvem calor do ambiente.", true),
      sel("A função orgânica do ácido acético é:", ["Ácido carboxílico", "Álcool", "Amida", "Éter"], 0),
      sel("Concentração comum é medida em:", ["g/L", "mol", "K", "atm"], 0),
      sel("Alótropos do carbono incluem:", ["Diamante e grafite", "Ferro e aço", "Água e gelo", "Sal e açúcar"], 0),
    ],
  },
  biologia: {
    all: [
      sel("Os ribossomos são responsáveis pela:", ["Síntese de proteínas", "Respiração", "Digestão celular", "Fotossíntese"], 0),
      sel("A meiose produz:", ["Quatro células com metade dos cromossomos", "Duas células idênticas", "Uma célula", "Células sem núcleo"], 0),
      sel("O RNA difere do DNA por conter:", ["Uracila e ribose", "Timina e desoxirribose", "Só timina", "Nenhum açúcar"], 0),
      sel("Os vírus são considerados:", ["Parasitas intracelulares obrigatórios", "Bactérias grandes", "Fungos", "Protozoários"], 0),
      sel("O sistema imunológico produz:", ["Anticorpos", "Hormônios digestivos", "Bile", "Ureia"], 0),
      sel("Cadeia alimentar: os decompositores atuam sobre:", ["Matéria orgânica morta", "Somente plantas vivas", "Rochas", "Água"], 0),
      sel("A fotossíntese libera:", ["Oxigênio", "Gás carbônico", "Nitrogênio", "Metano"], 0),
      sel("Segundo Mendel, na 1ª lei, os fatores se separam na:", ["Formação dos gametas", "Fecundação", "Mitose", "Digestão"], 0),
      tf("Biomas diferentes apresentam diferentes níveis de biodiversidade.", true),
      sel("O órgão responsável por filtrar o sangue é:", ["O rim", "O pulmão", "O estômago", "A pele"], 0),
      sel("Seleção natural favorece indivíduos:", ["Mais adaptados ao ambiente", "Maiores sempre", "Mais jovens", "Aleatórios"], 0),
      sel("Uma população é definida como:", ["Indivíduos da mesma espécie em um local", "Todas as espécies do planeta", "Só plantas", "Um ecossistema"], 0),
    ],
  },
  literatura: {
    all: [
      sel("O Trovadorismo é marcado pelas:", ["Cantigas medievais", "Crônicas urbanas", "Romances realistas", "Poesia concreta"], 0),
      sel("Gregório de Matos é poeta do:", ["Barroco", "Romantismo", "Modernismo", "Parnasianismo"], 0),
      sel("Iracema é obra de:", ["José de Alencar", "Machado de Assis", "Aluísio Azevedo", "Euclides da Cunha"], 0),
      sel("O Parnasianismo valorizava:", ["A forma e o rigor métrico", "O verso livre", "A prosa científica", "O regionalismo"], 0),
      sel("Os Sertões é de:", ["Euclides da Cunha", "Lima Barreto", "Castro Alves", "Álvares de Azevedo"], 0),
      sel("Macunaíma foi escrito por:", ["Mário de Andrade", "Oswald de Andrade", "Manuel Bandeira", "Clarice Lispector"], 0),
      sel("Clarice Lispector é conhecida por:", ["Narrativas introspectivas", "Poesia épica", "Teatro clássico", "Cordéis"], 0),
      sel("O Simbolismo se caracteriza por:", ["Musicalidade e sinestesia", "Objetividade científica", "Métrica rígida", "Realismo social"], 0),
      tf("Castro Alves ficou conhecido como o poeta dos escravos.", true),
      sel("A Geração de 45 buscou:", ["Maior rigor formal na poesia", "Ruptura total", "Prosa jornalística", "Cordel"], 0),
      sel("Capitu é personagem de:", ["Dom Casmurro", "O Cortiço", "Senhora", "Grande Sertão: Veredas"], 0),
      sel("Grande Sertão: Veredas é de:", ["Guimarães Rosa", "Jorge Amado", "Érico Veríssimo", "Rachel de Queiroz"], 0),
    ],
  },
  filosofia: {
    all: [
      sel("A maiêutica socrática consiste em:", ["Fazer perguntas para o outro chegar à verdade", "Impor respostas", "Escrever tratados", "Meditar em silêncio"], 0),
      sel("Aristóteles definiu o ser humano como:", ["Animal político", "Máquina", "Puro espírito", "Tábula rasa"], 0),
      sel("Para Hobbes, no estado de natureza:", ["O homem é o lobo do homem", "Reina a paz plena", "Não há conflito", "Todos são iguais e felizes"], 0),
      sel("O empirismo defende que o conhecimento vem:", ["Da experiência sensível", "Só da razão pura", "Da revelação", "Do acaso"], 0),
      sel("Nietzsche criticou:", ["A moral tradicional", "A física moderna", "A matemática", "A geografia"], 0),
      sel("Para Marx, a ideologia:", ["Mascara relações de dominação", "É neutra", "É ciência exata", "Não existe"], 0),
      sel("A ética utilitarista busca:", ["A maior felicidade para o maior número", "O dever pelo dever", "A virtude aristocrática", "A fé"], 0),
      tf("A lógica estuda a validade dos argumentos.", true),
      sel("Rousseau defendia que o homem nasce:", ["Bom e a sociedade o corrompe", "Mau por natureza", "Sem vontade", "Determinado por Deus"], 0),
      sel("Epistemologia é o estudo:", ["Do conhecimento", "Do belo", "Do ser", "Da política"], 0),
    ],
  },
  sociologia: {
    all: [
      sel("Anomia, para Durkheim, é:", ["Ausência de normas sociais claras", "Excesso de leis", "Igualdade total", "Um tipo de trabalho"], 0),
      sel("Mais-valia é conceito central de:", ["Marx", "Durkheim", "Weber", "Bourdieu"], 0),
      sel("Para Weber, a burocracia se baseia em:", ["Regras impessoais e hierarquia", "Laços familiares", "Sorte", "Carisma apenas"], 0),
      sel("Socialização primária ocorre principalmente na:", ["Família", "Empresa", "Universidade", "Igreja"], 0),
      sel("Estratificação social se refere a:", ["Divisão da sociedade em camadas", "Divisão geográfica", "Tipos de clima", "Grupos étnicos apenas"], 0),
      sel("Capital cultural é conceito de:", ["Bourdieu", "Comte", "Spencer", "Hobbes"], 0),
      sel("Indústria cultural foi discutida pela:", ["Escola de Frankfurt", "Escola de Chicago", "Positivismo", "Funcionalismo"], 0),
      tf("Preconceito e discriminação são fenômenos socialmente construídos.", true),
      sel("Democracia participativa envolve:", ["Envolvimento direto dos cidadãos", "Só eleições a cada 4 anos", "Governo de poucos", "Ausência de leis"], 0),
      sel("Etnocentrismo é:", ["Julgar outra cultura pelos valores da própria", "Respeitar toda cultura", "Estudar etnias", "Migrar"], 0),
    ],
  },
};
