/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DesafiosRouteImport } from './routes/desafios'
import { Route as EduIaRouteImport } from './routes/edu-ia'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as MateriasRouteImport } from './routes/materias'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PraticarRouteImport } from './routes/praticar'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RecuperarOfensivaRouteImport } from './routes/recuperar-ofensiva'
import { Route as TrilhaRouteImport } from './routes/trilha'
import { Route as AuthenticatedAmigosRouteImport } from './routes/_authenticated/amigos'
import { Route as LicaoLessonIdRouteImport } from './routes/licao.$lessonId'
import { Route as AuthenticatedAdminPagamentosRouteImport } from './routes/_authenticated/admin/pagamentos'
import { Route as AuthenticatedBatalhaBattleIdRouteImport } from './routes/_authenticated/batalha.$battleId'
import { Route as ApiEduChatRouteImport } from './routes/api/edu/chat'
import { Route as ApiPublicPicpayRouteImport } from './routes/api/public/picpay'
import { Route as ProvaSubjectIdUnitIndexRouteImport } from './routes/prova.$subjectId.$unitIndex'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosRoute = DesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => rootRouteImport,
} as any)
const EduIaRoute = EduIaRouteImport.update({
  id: '/edu-ia',
  path: '/edu-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasRoute = MateriasRouteImport.update({
  id: '/materias',
  path: '/materias',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PraticarRoute = PraticarRouteImport.update({
  id: '/praticar',
  path: '/praticar',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarOfensivaRoute = RecuperarOfensivaRouteImport.update({
  id: '/recuperar-ofensiva',
  path: '/recuperar-ofensiva',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhaRoute = TrilhaRouteImport.update({
  id: '/trilha',
  path: '/trilha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAmigosRoute = AuthenticatedAmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LicaoLessonIdRoute = LicaoLessonIdRouteImport.update({
  id: '/licao/$lessonId',
  path: '/licao/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPagamentosRoute =
  AuthenticatedAdminPagamentosRouteImport.update({
    id: '/admin/pagamentos',
    path: '/admin/pagamentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBatalhaBattleIdRoute =
  AuthenticatedBatalhaBattleIdRouteImport.update({
    id: '/batalha/$battleId',
    path: '/batalha/$battleId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiEduChatRoute = ApiEduChatRouteImport.update({
  id: '/api/edu/chat',
  path: '/api/edu/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPicpayRoute = ApiPublicPicpayRouteImport.update({
  id: '/api/public/picpay',
  path: '/api/public/picpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvaSubjectIdUnitIndexRoute = ProvaSubjectIdUnitIndexRouteImport.update({
  id: '/prova/$subjectId/$unitIndex',
  path: '/prova/$subjectId/$unitIndex',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/desafios': typeof DesafiosRoute
  '/edu-ia': typeof EduIaRoute
  '/loja': typeof LojaRoute
  '/materias': typeof MateriasRoute
  '/perfil': typeof PerfilRoute
  '/praticar': typeof PraticarRoute
  '/premium': typeof PremiumRoute
  '/ranking': typeof RankingRoute
  '/recuperar-ofensiva': typeof RecuperarOfensivaRoute
  '/trilha': typeof TrilhaRoute
  '/amigos': typeof AuthenticatedAmigosRoute
  '/licao/$lessonId': typeof LicaoLessonIdRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/batalha/$battleId': typeof AuthenticatedBatalhaBattleIdRoute
  '/api/edu/chat': typeof ApiEduChatRoute
  '/api/public/picpay': typeof ApiPublicPicpayRoute
  '/prova/$subjectId/$unitIndex': typeof ProvaSubjectIdUnitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/desafios': typeof DesafiosRoute
  '/edu-ia': typeof EduIaRoute
  '/loja': typeof LojaRoute
  '/materias': typeof MateriasRoute
  '/perfil': typeof PerfilRoute
  '/praticar': typeof PraticarRoute
  '/premium': typeof PremiumRoute
  '/ranking': typeof RankingRoute
  '/recuperar-ofensiva': typeof RecuperarOfensivaRoute
  '/trilha': typeof TrilhaRoute
  '/amigos': typeof AuthenticatedAmigosRoute
  '/licao/$lessonId': typeof LicaoLessonIdRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/batalha/$battleId': typeof AuthenticatedBatalhaBattleIdRoute
  '/api/edu/chat': typeof ApiEduChatRoute
  '/api/public/picpay': typeof ApiPublicPicpayRoute
  '/prova/$subjectId/$unitIndex': typeof ProvaSubjectIdUnitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/desafios': typeof DesafiosRoute
  '/edu-ia': typeof EduIaRoute
  '/loja': typeof LojaRoute
  '/materias': typeof MateriasRoute
  '/perfil': typeof PerfilRoute
  '/praticar': typeof PraticarRoute
  '/premium': typeof PremiumRoute
  '/ranking': typeof RankingRoute
  '/recuperar-ofensiva': typeof RecuperarOfensivaRoute
  '/trilha': typeof TrilhaRoute
  '/_authenticated/amigos': typeof AuthenticatedAmigosRoute
  '/licao/$lessonId': typeof LicaoLessonIdRoute
  '/_authenticated/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/_authenticated/batalha/$battleId': typeof AuthenticatedBatalhaBattleIdRoute
  '/api/edu/chat': typeof ApiEduChatRoute
  '/api/public/picpay': typeof ApiPublicPicpayRoute
  '/prova/$subjectId/$unitIndex': typeof ProvaSubjectIdUnitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/desafios'
    | '/edu-ia'
    | '/loja'
    | '/materias'
    | '/perfil'
    | '/praticar'
    | '/premium'
    | '/ranking'
    | '/recuperar-ofensiva'
    | '/trilha'
    | '/amigos'
    | '/licao/$lessonId'
    | '/admin/pagamentos'
    | '/batalha/$battleId'
    | '/api/edu/chat'
    | '/api/public/picpay'
    | '/prova/$subjectId/$unitIndex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/desafios'
    | '/edu-ia'
    | '/loja'
    | '/materias'
    | '/perfil'
    | '/praticar'
    | '/premium'
    | '/ranking'
    | '/recuperar-ofensiva'
    | '/trilha'
    | '/amigos'
    | '/licao/$lessonId'
    | '/admin/pagamentos'
    | '/batalha/$battleId'
    | '/api/edu/chat'
    | '/api/public/picpay'
    | '/prova/$subjectId/$unitIndex'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/desafios'
    | '/edu-ia'
    | '/loja'
    | '/materias'
    | '/perfil'
    | '/praticar'
    | '/premium'
    | '/ranking'
    | '/recuperar-ofensiva'
    | '/trilha'
    | '/_authenticated/amigos'
    | '/licao/$lessonId'
    | '/_authenticated/admin/pagamentos'
    | '/_authenticated/batalha/$battleId'
    | '/api/edu/chat'
    | '/api/public/picpay'
    | '/prova/$subjectId/$unitIndex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DesafiosRoute: typeof DesafiosRoute
  EduIaRoute: typeof EduIaRoute
  LojaRoute: typeof LojaRoute
  MateriasRoute: typeof MateriasRoute
  PerfilRoute: typeof PerfilRoute
  PraticarRoute: typeof PraticarRoute
  PremiumRoute: typeof PremiumRoute
  RankingRoute: typeof RankingRoute
  RecuperarOfensivaRoute: typeof RecuperarOfensivaRoute
  TrilhaRoute: typeof TrilhaRoute
  LicaoLessonIdRoute: typeof LicaoLessonIdRoute
  ApiEduChatRoute: typeof ApiEduChatRoute
  ApiPublicPicpayRoute: typeof ApiPublicPicpayRoute
  ProvaSubjectIdUnitIndexRoute: typeof ProvaSubjectIdUnitIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios': {
      id: '/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof DesafiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edu-ia': {
      id: '/edu-ia'
      path: '/edu-ia'
      fullPath: '/edu-ia'
      preLoaderRoute: typeof EduIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias': {
      id: '/materias'
      path: '/materias'
      fullPath: '/materias'
      preLoaderRoute: typeof MateriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praticar': {
      id: '/praticar'
      path: '/praticar'
      fullPath: '/praticar'
      preLoaderRoute: typeof PraticarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-ofensiva': {
      id: '/recuperar-ofensiva'
      path: '/recuperar-ofensiva'
      fullPath: '/recuperar-ofensiva'
      preLoaderRoute: typeof RecuperarOfensivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilha': {
      id: '/trilha'
      path: '/trilha'
      fullPath: '/trilha'
      preLoaderRoute: typeof TrilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/amigos': {
      id: '/_authenticated/amigos'
      path: '/amigos'
      fullPath: '/amigos'
      preLoaderRoute: typeof AuthenticatedAmigosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/licao/$lessonId': {
      id: '/licao/$lessonId'
      path: '/licao/$lessonId'
      fullPath: '/licao/$lessonId'
      preLoaderRoute: typeof LicaoLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/pagamentos': {
      id: '/_authenticated/admin/pagamentos'
      path: '/admin/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AuthenticatedAdminPagamentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/batalha/$battleId': {
      id: '/_authenticated/batalha/$battleId'
      path: '/batalha/$battleId'
      fullPath: '/batalha/$battleId'
      preLoaderRoute: typeof AuthenticatedBatalhaBattleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/edu/chat': {
      id: '/api/edu/chat'
      path: '/api/edu/chat'
      fullPath: '/api/edu/chat'
      preLoaderRoute: typeof ApiEduChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/picpay': {
      id: '/api/public/picpay'
      path: '/api/public/picpay'
      fullPath: '/api/public/picpay'
      preLoaderRoute: typeof ApiPublicPicpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prova/$subjectId/$unitIndex': {
      id: '/prova/$subjectId/$unitIndex'
      path: '/prova/$subjectId/$unitIndex'
      fullPath: '/prova/$subjectId/$unitIndex'
      preLoaderRoute: typeof ProvaSubjectIdUnitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAmigosRoute: typeof AuthenticatedAmigosRoute
  AuthenticatedAdminPagamentosRoute: typeof AuthenticatedAdminPagamentosRoute
  AuthenticatedBatalhaBattleIdRoute: typeof AuthenticatedBatalhaBattleIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAmigosRoute: AuthenticatedAmigosRoute,
  AuthenticatedAdminPagamentosRoute: AuthenticatedAdminPagamentosRoute,
  AuthenticatedBatalhaBattleIdRoute: AuthenticatedBatalhaBattleIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  DesafiosRoute: DesafiosRoute,
  EduIaRoute: EduIaRoute,
  LojaRoute: LojaRoute,
  MateriasRoute: MateriasRoute,
  PerfilRoute: PerfilRoute,
  PraticarRoute: PraticarRoute,
  PremiumRoute: PremiumRoute,
  RankingRoute: RankingRoute,
  RecuperarOfensivaRoute: RecuperarOfensivaRoute,
  TrilhaRoute: TrilhaRoute,
  LicaoLessonIdRoute: LicaoLessonIdRoute,
  ApiEduChatRoute: ApiEduChatRoute,
  ApiPublicPicpayRoute: ApiPublicPicpayRoute,
  ProvaSubjectIdUnitIndexRoute: ProvaSubjectIdUnitIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
