/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MateriasRouteImport } from './routes/materias'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PraticarRouteImport } from './routes/praticar'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as LicaoLessonIdRouteImport } from './routes/licao.$lessonId'
import { Route as ProvaSubjectIdUnitIndexRouteImport } from './routes/prova.$subjectId.$unitIndex'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasRoute = MateriasRouteImport.update({
  id: '/materias',
  path: '/materias',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PraticarRoute = PraticarRouteImport.update({
  id: '/praticar',
  path: '/praticar',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const LicaoLessonIdRoute = LicaoLessonIdRouteImport.update({
  id: '/licao/$lessonId',
  path: '/licao/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvaSubjectIdUnitIndexRoute = ProvaSubjectIdUnitIndexRouteImport.update({
  id: '/prova/$subjectId/$unitIndex',
  path: '/prova/$subjectId/$unitIndex',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/materias': typeof MateriasRoute
  '/perfil': typeof PerfilRoute
  '/praticar': typeof PraticarRoute
  '/premium': typeof PremiumRoute
  '/licao/$lessonId': typeof LicaoLessonIdRoute
  '/prova/$subjectId/$unitIndex': typeof ProvaSubjectIdUnitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/materias': typeof MateriasRoute
  '/perfil': typeof PerfilRoute
  '/praticar': typeof PraticarRoute
  '/premium': typeof PremiumRoute
  '/licao/$lessonId': typeof LicaoLessonIdRoute
  '/prova/$subjectId/$unitIndex': typeof ProvaSubjectIdUnitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/materias': typeof MateriasRoute
  '/perfil': typeof PerfilRoute
  '/praticar': typeof PraticarRoute
  '/premium': typeof PremiumRoute
  '/licao/$lessonId': typeof LicaoLessonIdRoute
  '/prova/$subjectId/$unitIndex': typeof ProvaSubjectIdUnitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/materias'
    | '/perfil'
    | '/praticar'
    | '/premium'
    | '/licao/$lessonId'
    | '/prova/$subjectId/$unitIndex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/materias'
    | '/perfil'
    | '/praticar'
    | '/premium'
    | '/licao/$lessonId'
    | '/prova/$subjectId/$unitIndex'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/materias'
    | '/perfil'
    | '/praticar'
    | '/premium'
    | '/licao/$lessonId'
    | '/prova/$subjectId/$unitIndex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MateriasRoute: typeof MateriasRoute
  PerfilRoute: typeof PerfilRoute
  PraticarRoute: typeof PraticarRoute
  PremiumRoute: typeof PremiumRoute
  LicaoLessonIdRoute: typeof LicaoLessonIdRoute
  ProvaSubjectIdUnitIndexRoute: typeof ProvaSubjectIdUnitIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias': {
      id: '/materias'
      path: '/materias'
      fullPath: '/materias'
      preLoaderRoute: typeof MateriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praticar': {
      id: '/praticar'
      path: '/praticar'
      fullPath: '/praticar'
      preLoaderRoute: typeof PraticarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licao/$lessonId': {
      id: '/licao/$lessonId'
      path: '/licao/$lessonId'
      fullPath: '/licao/$lessonId'
      preLoaderRoute: typeof LicaoLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prova/$subjectId/$unitIndex': {
      id: '/prova/$subjectId/$unitIndex'
      path: '/prova/$subjectId/$unitIndex'
      fullPath: '/prova/$subjectId/$unitIndex'
      preLoaderRoute: typeof ProvaSubjectIdUnitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MateriasRoute: MateriasRoute,
  PerfilRoute: PerfilRoute,
  PraticarRoute: PraticarRoute,
  PremiumRoute: PremiumRoute,
  LicaoLessonIdRoute: LicaoLessonIdRoute,
  ProvaSubjectIdUnitIndexRoute: ProvaSubjectIdUnitIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
